### ISSUE TITLE
Unable to create Hubot

### ISSUE THREAD

**Issue by mskutin** [spajus/hubot-control#15]
Ran hubot-control container from non-root user but with docker privileges.

![image](https://cloud.githubusercontent.com/assets/11622907/9712621/6b531db4-557e-11e5-8349-41c667b54640.png)

Obviously system user is root, but according to Dockerfile:
```Dockerfile
RUN useradd -m hubot

EXPOSE 3000

WORKDIR /usr/src/app
RUN chown -R hubot:hubot /usr/src/app

USER hubot
RUN RAILS_ENV=production bundle exec rake assets:precompile
```

**Comment by modist** [comment]
having same issue -did you ever found a fix ?

**Comment by mskutin** [comment]
@modist Nope, gave up for a long time ago. Besides this repo looks discontinued and abandoned.
If you solve this somehow let me know please.

**Comment by spajus** [comment]
> Besides this repo looks discontinued and abandoned.

It is abandoned, but I would be happy to add new owners if someone would step up to do the maintenance.

As of docker issue with root should be trivial to fix the issue or at least add some circumvention of the requirement - user detection is here: https://github.com/spajus/hubot-control/blob/master/app/models/status.rb#L44 - Feel free to open a PR.

**Comment by wazoo** [comment]
I opened PR #18 for this issue.

**Comment by wazoo** [comment]
I have merged the fixes to remove the root detection entirely since there are situations where this might be intentional (running as root for some sort of access reason for your bots) or abstracted (docker).  Might look at adding this back in as a warning later but really I think its fine.
